# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171717)
$foreground = rgb(E2E2E2)
$color0 = rgb(3E3E3E)
$color1 = rgb(111111)
$color2 = rgb(181818)
$color3 = rgb(464646)
$color4 = rgb(494949)
$color5 = rgb(6D6D6D)
$color6 = rgb(828282)
$color7 = rgb(CDCDCD)
$color8 = rgb(909090)
$color9 = rgb(171717)
$color10 = rgb(202020)
$color11 = rgb(5E5E5E)
$color12 = rgb(626262)
$color13 = rgb(919191)
$color14 = rgb(ADADAD)
$color15 = rgb(CDCDCD)
