# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E2E2E2
background         #171717
cursor             #818181

active_tab_foreground     #171717
active_tab_background     #E2E2E2
inactive_tab_foreground   #E2E2E2
inactive_tab_background   #171717

active_border_color   #E2E2E2
inactive_border_color #171717
bell_border_color     #111111

color0      #3E3E3E
color1		#111111
color2		#181818
color3		#464646
color4		#494949
color5		#6D6D6D
color6		#828282
color7		#CDCDCD
color8		#909090
color9		#171717
color10		#202020
color11		#5E5E5E
color12		#626262
color13		#919191
color14		#ADADAD
color15		#CDCDCD
