return {
  ensure_installed = {
    "lua",
    "python",
    "javascript",
    "typescript",
    "vimdoc",
    "vim",
    "regex",
    "terraform",
    "sql",
    "dockerfile",
    "toml",
    "json",
    "java",
    "groovy",
    "go",
    "gitignore",
    "graphql",
    "yaml",
    "make",
    "cmake",
    "markdown",
    "markdown_inline",
    "bash",
    "tsx",
    "css",
    "html",
    "rust",
  },
  auto_install = true,
  highlight = {
    use_languagetree = true,
    enable = true,
    additional_vim_regex_highlighting = { "ruby" },
  },
  indent = { enable = true, disable = { "ruby" } },
}
